accepted_content_types:
- text/html
- application/xhtml+xml
- text/plain
- text/xml
- application/xml
- application/json
base_url: https://www.techbend.io
binary_extensions:
- .pdf
- .zip
- .exe
- .tar
- .tar.gz
- .tgz
- .rar
- .iso
- .bin
- .7z
- .dmg
- .tar.xz
- .pkg
- .bz2
connection_string: sqlite:///python.db
db_path: python.db
delay: 1
depth_settings: {}
download_binaries: false
download_specific_binaries: []
exclude_content_patterns: []
exclude_url_patterns: []
find_images: false
generate_sitemap: true
llm:
  endpoint: http://localhost:1234/v1/chat/completions
  llm_prompt_template: Please summarize the following webpage content and extract
    a list of relevant tags. Return your answer as JSON with keys 'summary' and 'tags'.
  max_tokens: 16529
  model: jinaai.readerlm-v2@q4_k_m
  system_prompt: You are a helpful assistant that summarizes webpages and extracts
    tags.
  temperature: 0.7
log_file: techbend.log
max_depth: 2
recursive_crawl: true
respect_robots: true
save: true
url_settings: {}
verbose: true
